name: Multiple Jobs - Ulises

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}" ./node-app

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"

  run-and-test:
    runs-on: self-hosted
    needs: build-and-push 
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull "${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"

      - name: Run container
        run: docker run -d -p 8080:8080 --name final-node "${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"

      - name: Wait for container
        run: sleep 5

      - name: Test container with curl
        run: |
          $response = curl http://localhost:8080
          Write-Host "Full response:"
          Write-Host $response
          if ($response.Content -eq "Hello, CI Pipeline!") {
              Write-Host "Test passed"
          } else {
              Write-Host "Test failed"
              exit 1
          }

      - name: Save container logs
        run: docker logs final-node > container.log

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-node-logs
          path: container.log

      - name: Stop and remove container
        run: |
          docker stop final-node
          docker rm final-node
